### ISSUE TITLE
请问，本工具处理的是否是radm2机制的数据？

### ISSUE THREAD

**Issue by IncubatorShokuhou** [jinfan0931/meic2wrf#1]
请问有无namelist.input可供参考？
另外请问后续是否有适配其他化学机制的打算？

**Comment by jinfan0931** [comment]
完了可以上传个namelist。本工具物种转换是radm2。在wrf-chem中，chem_opt有某些选项，可以把radn2机制的物种转成选择的机制。还有一种方法，就是将代码中物种转换赋值的代码段按照所需机制进行更改。后续有时间还会谢一些小工具来方便wrf-chem的运行。谢谢支持！

**Comment by Sarah9804** [comment]
您好，非常感谢您的分享。但是有一个问题想请教一下，请问您的工具选择是RADM2，但是为什么namelist.input中的chem_opt选的却是10（CBMZ/MOSAIC）呢？

**Comment by IncubatorShokuhou** [comment]
@Sarah9804 
个人理解的：namelist中的chem_opt是wrfchem里面运行时候的化学机制。
emiss_opt是convert_emiss.exe生成排放数据文件的选项。
emiss_inpt_opt这个选项是决定了你怎么读排放源文件。就我个人理解，应该是和chem_opt没有太大关系的。
@jinfan0931 请指正。

**Comment by zxdawn** [comment]
我之前整理过两者的区别和使用方法：https://dreambooker.site/2020/03/10/Map-MEIC-to-MOZCART/

可以参考一下。

代码见[MEIC](https://github.com/zxdawn/pyXZ/tree/master/XZ_model/MEIC)

**Comment by Sarah9804** [comment]
好的，非常感谢您们

**Comment by Ccyyyyy** [comment]
感谢各位大佬的解答

**Comment by luchen28** [comment]
请问各位大佬，将meic2wrf针对的RADM2机制转化为CBMZ，emiss_opt和emiss_inpt_opt分别选哪一个选项？
